### ISSUE TITLE
Why is this white listed?

### ISSUE THREAD

**Issue by NN33NN** [PracticalChip/Adblocking#1]
Many host from this domain *.amazon-adsystem.com 

mads.amazon-adsystem.com

**Comment by NN33NN** [comment]
Also this one:
tpc.googlesyndication.com

Known to send ads

**Comment by PracticalChip** [comment]
mads.amazon is unblocked to allow the amazon mobile app to work

tpc.googlesyndication.com is one of the(I believe, i added so many "unbreaks" from google) map's adservers, that breaks maps if its not unblocked.
